sudo: required
dist: xenial
language: python
virtualenv:
  system_site_package: true
cache: pip
python:
- '3.4'
install:
- pip install -r requirements.txt
script: python tests/AppTestSuite.py
after_script: cd ~
